In [1]:
import pandas as pd
import numpy as np
import datetime
import math
from datetime import date
from dateutil import relativedelta
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [7]:
newallabpm = pd.read_csv("C:/Users/lala7/Desktop/Github/Lab/ABPM/1. interval avg prediction/Part 1 best bp combination/data preprocessing/input/newallabpm.csv") #(53982, 17)
newallabpm.shape

(53982, 17)

In [8]:
newallabpm

,New_MRN,Visit_Date,afib,SBP,DBP,pp,sbpvalid,dbpvalid,newdate,NEWTIME,NEWDATETIME,NEWSEQ,NEWVERSION,edittime,measureTime_int,measure_New,check
0,CGMHLK0001,2014/6/18,NaN,115.0,65.0,50.0,1,1,17-Jun-14,15:34,17JUN14:15:34:00,1,1,0,15,15.0,NaN
1,CGMHLK0001,2014/6/18,NaN,NaN,NaN,NaN,0,0,17-Jun-14,16:09,17JUN14:16:09:00,2,1,0,16,NaN,NaN
2,CGMHLK0001,2014/6/18,NaN,131.0,64.0,67.0,1,1,17-Jun-14,16:30,17JUN14:16:30:00,3,1,0,16,16.0,NaN
3,CGMHLK0001,2014/6/18,NaN,120.0,66.0,54.0,1,1,17-Jun-14,17:03,17JUN14:17:03:00,4,1,0,17,17.0,NaN
4,CGMHLK0001,2014/6/18,NaN,124.0,67.0,57.0,1,1,17-Jun-14,17:30,17JUN14:17:30:00,5,1,0,17,17.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53977,VGHTPE0312,2016/12/5,NaN,134.0,68.0,66.0,1,1,13-Aug-16,15:45,13AUG16:15:45:00,31,2,0,15,15.0,NaN
53978,VGHTPE0312,2016/12/5,NaN,131.0,77.0,54.0,1,1,13-Aug-16,16:00,13AUG16:16:00:00,32,2,0,16,16.0,NaN
53979,VGHTPE0312,2016/12/5,NaN,134.0,84.0,50.0,1,1,13-Aug-16,16:15,13AUG16:16:15:00,33,2,0,16,16.0,NaN
53980,VGHTPE0312,2016/12/5,NaN,134.0,71.0,63.0,1,1,13-Aug-16,16:30,13AUG16:16:30:00,34,2,0,16,16.0,NaN
53981,VGHTPE0312,2016/12/5,NaN,138.0,69.0,69.0,1,1,13-Aug-16,16:45,13AUG16:16:45:00,35,2,0,16,16.0,NaN

In [9]:
dfByMeasureValue = newallabpm.reset_index().pivot_table(index=['New_MRN', 'Visit_Date', 'NEWVERSION'], columns='measureTime_int', values='SBP', aggfunc=np.mean, fill_value=np.nan)
dfByMeasureValue = dfByMeasureValue.round(3)

In [10]:
dfByMeasureValue

measureTime_int                      0      1      2      3      4      5   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1             NaN  145.0    NaN  130.0  149.0  115.0
           2014/6/18  1           120.0  119.0  133.5    NaN  132.5    NaN
           2015/1/8   1           130.0  123.0  118.0  134.0  106.0    NaN
           2015/8/4   1           131.0  116.0  151.0    NaN  148.0  139.0
CGMHLK0002 2014/10/27 1           115.0  120.0  105.0  114.0  109.0  121.0
...                                 ...    ...    ...    ...    ...    ...
VGHTPE0347 2017/4/30  1             NaN    NaN    NaN    NaN    NaN    NaN
VGHTPE0348 2017/4/30  1            90.5   98.5   87.0   87.0   93.0   98.0
VGHTPE0349 2017/4/30  1             NaN    NaN    NaN    NaN    NaN  122.5
VGHTPE0350 2017/4/30  1             NaN  112.0    NaN    NaN    NaN    NaN
VGHTPE0351 2017/4/30  1           116.5  125.0  121.0  113.5  115.5  123.0

measureTime_int                      6        7        8      9   ...      14  \
New_MRN    Visit_Date NEWVERSION                                  ...
CGMHLK0001 2014/12/15 1             NaN  126.000      NaN  130.0  ...  142.00
           2014/6/18  1           112.5  128.000  128.000  140.5  ...     NaN
           2015/1/8   1           162.0  149.000  126.000  124.0  ...  114.50
           2015/8/4   1           139.5  143.000  145.500  138.5  ...     NaN
CGMHLK0002 2014/10/27 1           126.5  110.500  117.500  108.5  ...  121.00
...                                 ...      ...      ...    ...  ...     ...
VGHTPE0347 2017/4/30  1             NaN      NaN      NaN  168.0  ...  155.75
VGHTPE0348 2017/4/30  1           107.0  109.667  104.667  106.5  ...     NaN
VGHTPE0349 2017/4/30  1           124.0  135.750  130.250  130.0  ...  110.75
VGHTPE0350 2017/4/30  1             NaN      NaN      NaN    NaN  ...  130.25
VGHTPE0351 2017/4/30  1           123.0  127.750  141.500  138.5  ...     NaN

measureTime_int                      15     16      17      18      19  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           128.5  121.0     NaN  137.00  135.50
           2014/6/18  1           115.0  131.0  122.00  125.50  135.00
           2015/1/8   1           129.0    NaN  137.50  129.00  126.00
           2015/8/4   1           128.0  115.5  128.00  141.00  144.00
CGMHLK0002 2014/10/27 1           127.0  117.5  120.50  117.50  114.50
...                                 ...    ...     ...     ...     ...
VGHTPE0347 2017/4/30  1           166.0  144.5  152.50  152.75  173.00
VGHTPE0348 2017/4/30  1             NaN    NaN     NaN     NaN     NaN
VGHTPE0349 2017/4/30  1           113.5  124.0     NaN     NaN     NaN
VGHTPE0350 2017/4/30  1           129.5  135.5  138.75  139.25  133.25
VGHTPE0351 2017/4/30  1             NaN    NaN     NaN     NaN     NaN

measureTime_int                        20       21     22     23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  121.000  129.0  119.0
           2014/6/18  1           136.000      NaN  123.0  133.0
           2015/1/8   1           135.000  147.500  119.0  126.0
           2015/8/4   1           133.000  131.500  144.0  123.0
CGMHLK0002 2014/10/27 1           111.000  108.000   97.0  118.0
...                                   ...      ...    ...    ...
VGHTPE0347 2017/4/30  1               NaN      NaN    NaN    NaN
VGHTPE0348 2017/4/30  1           107.667   96.500   91.5   93.0
VGHTPE0349 2017/4/30  1               NaN      NaN    NaN    NaN
VGHTPE0350 2017/4/30  1           132.250  131.333  132.5  134.0
VGHTPE0351 2017/4/30  1               NaN      NaN  143.0  135.5

[1601 rows x 24 columns]

# 丟掉缺失值

In [11]:
# TCHC 各個時間點bp缺失值排序：缺失比例最多的時間點依序為 9am, 8am, 10am, 7am, 6am
dfByMeasureValue.isnull().sum().sort_values(ascending=False)

measureTime_int
9     571
8     564
10    449
7     441
6     409
5     407
4     366
3     350
11    329
2     324
22    323
23    319
1     302
0     301
12    267
21    261
13    248
14    247
15    245
16    241
17    234
18    228
20    225
19    212
dtype: int64

### 1. 丟掉所有存在缺失值的樣本

In [12]:
df_drop_all_nan = dfByMeasureValue.dropna()
df_drop_all_nan.to_csv("./preprocessed data/drop_all_nan.csv")
df_drop_all_nan # 142 rows × 24 columns

measureTime_int                      0      1      2      3      4      5   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0003 2014/12/15 1            95.5   94.5   86.0   91.0   87.0   86.0
           2015/3/24  1           104.0  113.0   98.0   94.0   94.0   91.0
CGMHLK0004 2014/10/27 1            91.0  118.0  108.0  107.0   87.0  121.0
CGMHLK0007 2014/7/9   1           107.0  100.0  118.0  103.0   99.0  106.0
CGMHLK0012 2014/7/25  1           128.0  127.0  143.0  127.0  149.0  122.0
...                                 ...    ...    ...    ...    ...    ...
NTUH130179 2014/6/24  1           129.0  122.0  127.0  137.0  145.0  149.0
NTUH130198 2014/7/14  1           123.0  120.0  108.0  119.0  119.0  125.0
NTUH130283 2014/7/15  1           124.0  134.0  139.0  130.0  112.0  131.0
NTUH130330 2014/12/9  1            99.0   86.0  101.0  107.0   97.0   79.0
NTUH140359 2014/6/27  1           127.0  119.0  121.0  126.0  119.0  116.0

measureTime_int                        6      7      8        9   ...     14  \
New_MRN    Visit_Date NEWVERSION                                  ...
CGMHLK0003 2014/12/15 1            92.333   95.5  106.0  113.667  ...  114.0
           2015/3/24  1           107.500  120.0  113.0  107.000  ...   95.5
CGMHLK0004 2014/10/27 1           105.000   81.0   88.5   92.000  ...   84.0
CGMHLK0007 2014/7/9   1           108.000  110.0  106.5  129.000  ...  115.0
CGMHLK0012 2014/7/25  1           116.000  129.0  112.5  123.000  ...  116.0
...                                   ...    ...    ...      ...  ...    ...
NTUH130179 2014/6/24  1           125.000  145.0  139.0  114.500  ...  137.5
NTUH130198 2014/7/14  1           121.000  135.0  123.0  127.000  ...  119.0
NTUH130283 2014/7/15  1           121.000  130.0  136.0  133.000  ...  114.0
NTUH130330 2014/12/9  1            90.000  101.0   95.0  123.000  ...  125.0
NTUH140359 2014/6/27  1           115.000  112.0  124.0  112.000  ...  106.0

measureTime_int                        15       16      17      18     19  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0003 2014/12/15 1           106.333   98.333   94.75  103.25  106.5
           2015/3/24  1           113.000   99.500  103.00  100.00  117.5
CGMHLK0004 2014/10/27 1            85.500  104.000  117.00  111.00  117.0
CGMHLK0007 2014/7/9   1           114.000  113.500  116.00  118.50  127.0
CGMHLK0012 2014/7/25  1           122.500  111.000  127.00  121.00  126.5
...                                   ...      ...     ...     ...    ...
NTUH130179 2014/6/24  1           130.000  140.000  121.00  141.00  176.0
NTUH130198 2014/7/14  1           132.000  146.000  141.00  144.00  136.0
NTUH130283 2014/7/15  1           125.000  113.000  121.00  137.00  136.0
NTUH130330 2014/12/9  1           121.000  119.000  124.00  121.00  132.0
NTUH140359 2014/6/27  1           115.000  134.000  135.00  138.00  139.0

measureTime_int                       20      21     22     23
New_MRN    Visit_Date NEWVERSION
CGMHLK0003 2014/12/15 1           104.25  111.75  112.0  106.5
           2015/3/24  1           121.00  118.00  107.0  112.0
CGMHLK0004 2014/10/27 1           102.50  106.00   92.0  100.0
CGMHLK0007 2014/7/9   1           119.50  130.00  130.0  130.0
CGMHLK0012 2014/7/25  1           136.00  128.50  130.0  120.0
...                                  ...     ...    ...    ...
NTUH130179 2014/6/24  1           166.00  154.00  152.0  133.0
NTUH130198 2014/7/14  1           130.00  128.00  137.0  116.0
NTUH130283 2014/7/15  1           118.00  132.00  128.0  132.0
NTUH130330 2014/12/9  1           122.00  105.00  106.0  111.0
NTUH140359 2014/6/27  1           133.00  126.00  133.0  127.0

[142 rows x 24 columns]

### 2. 先取前後各一個時間平均做為補值，再丟掉有缺失值的樣本（連續多個NAN）

In [13]:
def replace_nan_with_two_average(row, col):
    if pd.isna(row[col]):
        if col > 0 and col < 23:
            other_columns = [col-1, col+1]
        elif col == 23:
            other_columns = [22, 0]
        elif col == 0:
            other_columns = [23, 1]        
        return np.nanmean(row[other_columns])
    else:
        return row[col]

In [14]:
df_drop_two_nan = dfByMeasureValue.copy()
df_drop_two_nan = df_drop_two_nan[~df_drop_two_nan.index.isin(df_drop_two_nan.dropna().index)]

In [15]:
for column in df_drop_two_nan.columns:
    df_drop_two_nan[column] = df_drop_two_nan.apply(lambda row: replace_nan_with_two_average(row, column), axis=1)

In [16]:
df_drop_two_nan = df_drop_two_nan.dropna()
df_drop_two_nan.to_csv("./preprocessed data/two_avg_drop_nan.csv")
df_drop_two_nan # 1401 rows × 24 columns

measureTime_int                      0      1      2      3      4      5   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           132.0  145.0  137.5  130.0  149.0  115.0
           2014/6/18  1           120.0  119.0  133.5  133.0  132.5  122.5
           2015/1/8   1           130.0  123.0  118.0  134.0  106.0  134.0
           2015/8/4   1           131.0  116.0  151.0  149.5  148.0  139.0
CGMHLK0002 2014/10/27 1           115.0  120.0  105.0  114.0  109.0  121.0
...                                 ...    ...    ...    ...    ...    ...
VGHTPE0345 2017/4/30  1           136.5  147.0  127.0  139.0  142.5  140.0
VGHTPE0346 2017/4/30  1           101.5  115.0  123.5  123.5  115.5  118.0
VGHTPE0348 2017/4/30  1            90.5   98.5   87.0   87.0   93.0   98.0
VGHTPE0350 2017/4/30  1           123.0  112.0  112.0  112.0  112.0  112.0
VGHTPE0351 2017/4/30  1           116.5  125.0  121.0  113.5  115.5  123.0

measureTime_int                       6        7        8      9   ...  \
New_MRN    Visit_Date NEWVERSION                                   ...
CGMHLK0001 2014/12/15 1           120.50  126.000  128.000  130.0  ...
           2014/6/18  1           112.50  128.000  128.000  140.5  ...
           2015/1/8   1           162.00  149.000  126.000  124.0  ...
           2015/8/4   1           139.50  143.000  145.500  138.5  ...
CGMHLK0002 2014/10/27 1           126.50  110.500  117.500  108.5  ...
...                                  ...      ...      ...    ...  ...
VGHTPE0345 2017/4/30  1           136.25  133.250  142.000  148.5  ...
VGHTPE0346 2017/4/30  1           120.75  130.250  134.000  134.0  ...
VGHTPE0348 2017/4/30  1           107.00  109.667  104.667  106.5  ...
VGHTPE0350 2017/4/30  1           112.00  112.000  112.000  112.0  ...
VGHTPE0351 2017/4/30  1           123.00  127.750  141.500  138.5  ...

measureTime_int                       14      15      16      17      18  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           142.00  128.50  121.00  129.00  137.00
           2014/6/18  1           133.50  115.00  131.00  122.00  125.50
           2015/1/8   1           114.50  129.00  133.25  137.50  129.00
           2015/8/4   1           127.50  128.00  115.50  128.00  141.00
CGMHLK0002 2014/10/27 1           121.00  127.00  117.50  120.50  117.50
...                                  ...     ...     ...     ...     ...
VGHTPE0345 2017/4/30  1           151.50  151.50  151.50  151.50  151.50
VGHTPE0346 2017/4/30  1           119.75  119.75  119.75  119.75  119.75
VGHTPE0348 2017/4/30  1           108.00  108.00  108.00  108.00  108.00
VGHTPE0350 2017/4/30  1           130.25  129.50  135.50  138.75  139.25
VGHTPE0351 2017/4/30  1           160.00  160.00  160.00  160.00  160.00

measureTime_int                         19       20       21     22     23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           135.5000  115.000  121.000  129.0  119.0
           2014/6/18  1           135.0000  136.000  129.500  123.0  133.0
           2015/1/8   1           126.0000  135.000  147.500  119.0  126.0
           2015/8/4   1           144.0000  133.000  131.500  144.0  123.0
CGMHLK0002 2014/10/27 1           114.5000  111.000  108.000   97.0  118.0
...                                    ...      ...      ...    ...    ...
VGHTPE0345 2017/4/30  1           151.5000  151.500  151.500  151.5  144.0
VGHTPE0346 2017/4/30  1           119.7500  121.875  124.000  113.0  117.0
VGHTPE0348 2017/4/30  1           107.8335  107.667   96.500   91.5   93.0
VGHTPE0350 2017/4/30  1           133.2500  132.250  131.333  132.5  134.0
VGHTPE0351 2017/4/30  1           160.0000  160.000  151.500  143.0  135.5

[1259 rows x 24 columns]

### 3. 先取前後各兩個時間平均做為補值，再丟掉有缺失值的樣本（連續多個NAN）

In [17]:
def replace_nan_with_four_average(row, col):
    if pd.isna(row[col]):
        if col > 1 and col < 22:
            other_columns = [col-2, col-1, col+1, col+2]
        elif col == 0:
            other_columns = [22, 23, 1, 2]
        elif col == 1:
            other_columns = [23, 0, 2, 3]    
        elif col == 22:
            other_columns = [20, 21, 23, 0]
        elif col == 23:
            other_columns = [21, 22, 0, 1]       
        return np.nanmean(row[other_columns])
    else:
        return row[col]

In [18]:
df_drop_four_nan = dfByMeasureValue.copy()
df_drop_four_nan = df_drop_four_nan[~df_drop_four_nan.index.isin(df_drop_four_nan.dropna().index)] # 拿掉完整的142筆(training data)
for column in df_drop_four_nan.columns:
    df_drop_four_nan[column] = df_drop_four_nan.apply(lambda row: replace_nan_with_four_average(row, column), axis=1)

In [19]:
df_drop_four_nan = df_drop_four_nan.dropna()
df_drop_four_nan = df_drop_four_nan.round(3)
df_drop_four_nan.to_csv("./preprocessed data/four_avg_drop_nan.csv")
df_drop_four_nan # 1428 rows × 24 columns

measureTime_int                        0      1        2        3        4   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           131.000  145.0  138.750  130.000  149.000
           2014/6/18  1           120.000  119.0  133.500  128.333  132.500
           2015/1/8   1           130.000  123.0  118.000  134.000  106.000
           2015/8/4   1           131.000  116.0  151.000  138.500  148.000
CGMHLK0002 2014/10/27 1           115.000  120.0  105.000  114.000  109.000
...                                   ...    ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           136.500  147.0  127.000  139.000  142.500
VGHTPE0346 2017/4/30  1           101.500  115.0  123.500  123.500  115.500
VGHTPE0348 2017/4/30  1            90.500   98.5   87.000   87.000   93.000
VGHTPE0350 2017/4/30  1           126.167  112.0  119.083  115.542  117.312
VGHTPE0351 2017/4/30  1           116.500  125.0  121.000  113.500  115.500

measureTime_int                        5       6        7        8        9   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  130.00  126.000  129.625  130.000
           2014/6/18  1           125.333  112.50  128.000  128.000  140.500
           2015/1/8   1           137.750  162.00  149.000  126.000  124.000
           2015/8/4   1           139.000  139.50  143.000  145.500  138.500
CGMHLK0002 2014/10/27 1           121.000  126.50  110.500  117.500  108.500
...                                   ...     ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           140.000  136.25  133.250  142.000  148.500
VGHTPE0346 2017/4/30  1           118.000  120.75  130.250  134.000  122.750
VGHTPE0348 2017/4/30  1            98.000  107.00  109.667  104.667  106.500
VGHTPE0350 2017/4/30  1           116.427  116.87  116.648  116.759  116.704
VGHTPE0351 2017/4/30  1           123.000  123.00  127.750  141.500  138.500

measureTime_int                   ...       14       15       16       17  \
New_MRN    Visit_Date NEWVERSION  ...
CGMHLK0001 2014/12/15 1           ...  142.000  128.500  121.000  130.500
           2014/6/18  1           ...  133.769  115.000  131.000  122.000
           2015/1/8   1           ...  114.500  129.000  127.500  137.500
           2015/8/4   1           ...  127.250  128.000  115.500  128.000
CGMHLK0002 2014/10/27 1           ...  121.000  127.000  117.500  120.500
...                               ...      ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           ...  154.250  155.625  154.938  155.281
VGHTPE0346 2017/4/30  1           ...  114.208  116.979  115.594  116.287
VGHTPE0348 2017/4/30  1           ...  107.396  107.497  107.446  107.471
VGHTPE0350 2017/4/30  1           ...  130.250  129.500  135.500  138.750
VGHTPE0351 2017/4/30  1           ...  150.625  152.188  151.406  151.797

measureTime_int                        18       19       20       21       22  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           137.000  135.500  115.000  121.000  129.000
           2014/6/18  1           125.500  135.000  136.000  131.750  123.000
           2015/1/8   1           129.000  126.000  135.000  147.500  119.000
           2015/8/4   1           141.000  144.000  133.000  131.500  144.000
CGMHLK0002 2014/10/27 1           117.500  114.500  111.000  108.000   97.000
...                                   ...      ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           155.109  155.195  155.152  155.174  148.942
VGHTPE0346 2017/4/30  1           115.940  118.742  117.921  124.000  113.000
VGHTPE0348 2017/4/30  1           107.528  104.792  107.667   96.500   91.500
VGHTPE0350 2017/4/30  1           139.250  133.250  132.250  131.333  132.500
VGHTPE0351 2017/4/30  1           151.602  151.699  148.767  144.742  143.000

measureTime_int                        23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           119.000
           2014/6/18  1           133.000
           2015/1/8   1           126.000
           2015/8/4   1           123.000
CGMHLK0002 2014/10/27 1           118.000
...                                   ...
VGHTPE0345 2017/4/30  1           146.904
VGHTPE0346 2017/4/30  1           117.000
VGHTPE0348 2017/4/30  1            93.000
VGHTPE0350 2017/4/30  1           134.000
VGHTPE0351 2017/4/30  1           135.500

[1286 rows x 24 columns]

### 4. 先取前一個&後兩個時間平均做為補值，再丟掉有缺失值的樣本（連續多個NAN）

In [65]:
def replace_nan_with_three_average(row, col, more):
    if more == "next":
        if pd.isna(row[col]):
            if col > 0 and col < 22:
                other_columns = [col-1, col+1, col+2]
            elif col == 0:
                other_columns = [23, 1, 2]
            elif col == 22:
                other_columns = [21, 23, 0]
            elif col == 23:
                other_columns = [22, 0, 1]       
            return np.nanmean(row[other_columns])
        else:
            return row[col]
    else:
        if pd.isna(row[col]):
            if col > 1 and col < 23:
                other_columns = [col-2, col-1, col+1]
            elif col == 0:
                other_columns = [22, 23, 1]
            elif col == 1:
                other_columns = [23, 0, 2]
            elif col == 23:
                other_columns = [21, 22, 0]       
            return np.nanmean(row[other_columns])
        else:
            return row[col]

In [62]:
df_drop_three_nan = dfByMeasureValue.copy()
df_drop_three_nan = df_drop_three_nan[~df_drop_three_nan.index.isin(df_drop_three_nan.dropna().index)] # 拿掉完整的142筆(training data)
for column in df_drop_three_nan.columns:
    df_drop_three_nan[column] = df_drop_three_nan.apply(lambda row: replace_nan_with_three_average(row, column, "next"), axis=1)

In [63]:
df_drop_three_nan = df_drop_three_nan.dropna()
df_drop_three_nan = df_drop_three_nan.round(3)
df_drop_three_nan.to_csv("./preprocessed data/three_next_avg_drop_nan.csv")
df_drop_three_nan # 1404 rows × 24 columns

measureTime_int                      0      1        2      3      4   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           132.0  145.0  141.333  130.0  149.0
           2014/6/18  1           120.0  119.0  133.500  133.0  132.5
           2015/1/8   1           130.0  123.0  118.000  134.0  106.0
           2015/8/4   1           131.0  116.0  151.000  146.0  148.0
CGMHLK0002 2014/10/27 1           115.0  120.0  105.000  114.0  109.0
...                                 ...    ...      ...    ...    ...
VGHTPE0345 2017/4/30  1           136.5  147.0  127.000  139.0  142.5
VGHTPE0346 2017/4/30  1           101.5  115.0  123.500  123.5  115.5
VGHTPE0348 2017/4/30  1            90.5   98.5   87.000   87.0   93.0
VGHTPE0350 2017/4/30  1           123.0  112.0  112.000  112.0  112.0
VGHTPE0351 2017/4/30  1           116.5  125.0  121.000  113.5  115.5

measureTime_int                        5       6        7        8      9   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  120.50  126.000  129.500  130.0
           2014/6/18  1           124.333  112.50  128.000  128.000  140.5
           2015/1/8   1           139.000  162.00  149.000  126.000  124.0
           2015/8/4   1           139.000  139.50  143.000  145.500  138.5
CGMHLK0002 2014/10/27 1           121.000  126.50  110.500  117.500  108.5
...                                   ...     ...      ...      ...    ...
VGHTPE0345 2017/4/30  1           140.000  136.25  133.250  142.000  148.5
VGHTPE0346 2017/4/30  1           118.000  120.75  130.250  134.000  119.0
VGHTPE0348 2017/4/30  1            98.000  107.00  109.667  104.667  106.5
VGHTPE0350 2017/4/30  1           112.000  112.00  112.000  112.000  112.0
VGHTPE0351 2017/4/30  1           123.000  123.00  127.750  141.500  138.5

measureTime_int                   ...      14      15       16       17  \
New_MRN    Visit_Date NEWVERSION  ...
CGMHLK0001 2014/12/15 1           ...  142.00  128.50  121.000  131.167
           2014/6/18  1           ...  126.50  115.00  131.000  122.000
           2015/1/8   1           ...  114.50  129.00  131.833  137.500
           2015/8/4   1           ...  123.50  128.00  115.500  128.000
CGMHLK0002 2014/10/27 1           ...  121.00  127.00  117.500  120.500
...                               ...     ...     ...      ...      ...
VGHTPE0345 2017/4/30  1           ...  151.50  151.50  151.500  151.500
VGHTPE0346 2017/4/30  1           ...  119.75  119.75  119.750  119.750
VGHTPE0348 2017/4/30  1           ...  108.00  108.00  108.000  108.000
VGHTPE0350 2017/4/30  1           ...  130.25  129.50  135.500  138.750
VGHTPE0351 2017/4/30  1           ...  160.00  160.00  160.000  160.000

measureTime_int                        18       19       20       21     22  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           137.000  135.500  115.000  121.000  129.0
           2014/6/18  1           125.500  135.000  136.000  130.667  123.0
           2015/1/8   1           129.000  126.000  135.000  147.500  119.0
           2015/8/4   1           141.000  144.000  133.000  131.500  144.0
CGMHLK0002 2014/10/27 1           117.500  114.500  111.000  108.000   97.0
...                                   ...      ...      ...      ...    ...
VGHTPE0345 2017/4/30  1           151.500  151.500  151.500  151.500  144.0
VGHTPE0346 2017/4/30  1           119.750  121.875  119.625  124.000  113.0
VGHTPE0348 2017/4/30  1           107.834  104.000  107.667   96.500   91.5
VGHTPE0350 2017/4/30  1           139.250  133.250  132.250  131.333  132.5
VGHTPE0351 2017/4/30  1           160.000  160.000  151.500  143.333  143.0

measureTime_int                      23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           119.0
           2014/6/18  1           133.0
           2015/1/8   1           126.0
           2015/8/4   1           123.0
CGMHLK0002 2014/10/27 1           118.0
...                                 ...
VGHTPE0345 2017/4/30  1           142.5
VGHTPE0346 2017/4/30  1           117.0
VGHTPE0348 2017/4/30  1            93.0
VGHTPE0350 2017/4/30  1           134.0
VGHTPE0351 2017/4/30  1           135.5

[1262 rows x 24 columns]

In [66]:
df_drop_three_nan = dfByMeasureValue.copy()
df_drop_three_nan = df_drop_three_nan[~df_drop_three_nan.index.isin(df_drop_three_nan.dropna().index)] # 拿掉完整的142筆(training data)
for column in df_drop_three_nan.columns:
    df_drop_three_nan[column] = df_drop_three_nan.apply(lambda row: replace_nan_with_three_average(row, column, "pre"), axis=1)

In [67]:
df_drop_three_nan = df_drop_three_nan.dropna()
df_drop_three_nan = df_drop_three_nan.round(3)
df_drop_three_nan.to_csv("./preprocessed data/three_pre_avg_drop_nan.csv")
df_drop_three_nan # 1404 rows × 24 columns

measureTime_int                        0      1        2        3        4   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           131.000  145.0  135.333  130.000  149.000
           2014/6/18  1           120.000  119.0  133.500  128.333  132.500
           2015/1/8   1           130.000  123.0  118.000  134.000  106.000
           2015/8/4   1           131.000  116.0  151.000  138.333  148.000
CGMHLK0002 2014/10/27 1           115.000  120.0  105.000  114.000  109.000
...                                   ...    ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           136.500  147.0  127.000  139.000  142.500
VGHTPE0346 2017/4/30  1           101.500  115.0  123.500  123.500  115.500
VGHTPE0348 2017/4/30  1            90.500   98.5   87.000   87.000   93.000
VGHTPE0350 2017/4/30  1           126.167  112.0  119.083  115.542  117.312
VGHTPE0351 2017/4/30  1           116.500  125.0  121.000  113.500  115.500

measureTime_int                        5       6        7        8        9   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  130.00  126.000  128.667  130.000
           2014/6/18  1           124.444  112.50  128.000  128.000  140.500
           2015/1/8   1           134.000  162.00  149.000  126.000  124.000
           2015/8/4   1           139.000  139.50  143.000  145.500  138.500
CGMHLK0002 2014/10/27 1           121.000  126.50  110.500  117.500  108.500
...                                   ...     ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           140.000  136.25  133.250  142.000  148.500
VGHTPE0346 2017/4/30  1           118.000  120.75  130.250  134.000  132.125
VGHTPE0348 2017/4/30  1            98.000  107.00  109.667  104.667  106.500
VGHTPE0350 2017/4/30  1           116.427  116.87  116.648  116.759  116.704
VGHTPE0351 2017/4/30  1           123.000  123.00  127.750  141.500  138.500

measureTime_int                   ...       14       15       16       17  \
New_MRN    Visit_Date NEWVERSION  ...
CGMHLK0001 2014/12/15 1           ...  142.000  128.500  121.000  128.833
           2014/6/18  1           ...  138.042  115.000  131.000  122.000
           2015/1/8   1           ...  114.500  129.000  127.000  137.500
           2015/8/4   1           ...  131.167  128.000  115.500  128.000
CGMHLK0002 2014/10/27 1           ...  121.000  127.000  117.500  120.500
...                               ...      ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           ...  154.250  155.625  154.938  155.281
VGHTPE0346 2017/4/30  1           ...  114.208  116.979  115.594  116.287
VGHTPE0348 2017/4/30  1           ...  107.396  107.497  107.446  107.471
VGHTPE0350 2017/4/30  1           ...  130.250  129.500  135.500  138.750
VGHTPE0351 2017/4/30  1           ...  150.625  152.188  151.406  151.797

measureTime_int                        18       19       20       21       22  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           137.000  135.500  115.000  121.000  129.000
           2014/6/18  1           125.500  135.000  136.000  131.333  123.000
           2015/1/8   1           129.000  126.000  135.000  147.500  119.000
           2015/8/4   1           141.000  144.000  133.000  131.500  144.000
CGMHLK0002 2014/10/27 1           117.500  114.500  111.000  108.000   97.000
...                                   ...      ...      ...      ...      ...
VGHTPE0345 2017/4/30  1           155.109  155.195  155.152  155.174  155.163
VGHTPE0346 2017/4/30  1           115.940  116.113  118.685  124.000  113.000
VGHTPE0348 2017/4/30  1           107.459  107.532  107.667   96.500   91.500
VGHTPE0350 2017/4/30  1           139.250  133.250  132.250  131.333  132.500
VGHTPE0351 2017/4/30  1           151.602  151.699  151.650  148.783  143.000

measureTime_int                        23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           119.000
           2014/6/18  1           133.000
           2015/1/8   1           126.000
           2015/8/4   1           123.000
CGMHLK0002 2014/10/27 1           118.000
...                                   ...
VGHTPE0345 2017/4/30  1           148.946
VGHTPE0346 2017/4/30  1           117.000
VGHTPE0348 2017/4/30  1            93.000
VGHTPE0350 2017/4/30  1           134.000
VGHTPE0351 2017/4/30  1           135.500

[1285 rows x 24 columns]

## 5. 取前後兩個時間bp加權平均

In [42]:
def replace_nan_with_two_weighted(row, col):
    if pd.isna(row[col]):
        if col > 0 and col < 23:
            other_columns = [col-1, col+1]
        elif col == 23:
            other_columns = [22, 0]
        elif col == 0:
            other_columns = [23, 1] 
        weighted_avg = row[other_columns[1]] - (row[other_columns[1]]-row[other_columns[0]])*(row[other_columns[0]]/(row[other_columns[1]]+row[other_columns[0]]))
        return weighted_avg
    else:
        return row[col]

In [43]:
df_drop_two_nan_weighted = dfByMeasureValue.copy()
df_drop_two_nan_weighted = df_drop_two_nan_weighted[~df_drop_two_nan_weighted.index.isin(df_drop_two_nan_weighted.dropna().index)] # 拿掉完整的142筆(training data)
for column in df_drop_two_nan_weighted.columns:
    df_drop_two_nan_weighted[column] = df_drop_two_nan_weighted.apply(lambda row: replace_nan_with_two_weighted(row, column), axis=1)

In [44]:
df_drop_two_nan_weighted = df_drop_two_nan_weighted.dropna()
df_drop_two_nan_weighted = df_drop_two_nan_weighted.round(3)
df_drop_two_nan_weighted.to_csv("./preprocessed data/two_weighted_drop_nan.csv")
df_drop_two_nan_weighted # 1428 rows × 24 columns

measureTime_int                       0      1        2        3      4   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           133.28  145.0  137.909  130.000  149.0
           2015/1/8   1           130.00  123.0  118.000  134.000  106.0
           2015/8/4   1           131.00  116.0  151.000  149.515  148.0
CGMHLK0004 2015/3/24  1           112.00  119.0  121.000  114.000  123.0
CGMHLK0007 2014/10/27 1           138.00  123.0  108.000  110.557  113.0
...                                  ...    ...      ...      ...    ...
NTUH140353 2014/5/5   1            86.00   79.0   91.000   91.000   90.0
NTUH160379 2016/12/7  1            99.00  103.0  101.000   98.000   97.0
VGHTPE0001 2014/7/10  1           146.00  129.0  130.000  137.000  123.0
VGHTPE0003 2014/7/9   1           153.00  144.0  149.000  147.000  128.0
VGHTPE0078 2015/5/28  1           119.00  137.0  116.000  127.000  112.0

measureTime_int                        5        6      7        8      9   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  120.751  126.0  128.031  130.0
           2015/1/8   1           139.851  162.000  149.0  126.000  124.0
           2015/8/4   1           139.000  139.500  143.0  145.500  138.5
CGMHLK0004 2015/3/24  1           135.000  117.500  112.5   99.000  110.0
CGMHLK0007 2014/10/27 1           129.000  112.000  126.5  122.500  122.5
...                                   ...      ...    ...      ...    ...
NTUH140353 2014/5/5   1            91.000   95.000   95.5   90.500   84.0
NTUH160379 2016/12/7  1            94.000  108.500  105.5  103.000  108.5
VGHTPE0001 2014/7/10  1           141.000  150.000  153.5  135.500  131.0
VGHTPE0003 2014/7/9   1           161.000  131.000  150.5  141.500  142.5
VGHTPE0078 2015/5/28  1           113.000  116.000  123.0  132.049  140.0

measureTime_int                   ...       14      15       16       17  \
New_MRN    Visit_Date NEWVERSION  ...
CGMHLK0001 2014/12/15 1           ...  142.000  128.50  121.000  129.496
           2015/1/8   1           ...  114.500  129.00  133.386  137.500
           2015/8/4   1           ...  127.502  128.00  115.500  128.000
CGMHLK0004 2015/3/24  1           ...   98.500  106.50  114.500  126.000
CGMHLK0007 2014/10/27 1           ...  117.000  116.00  117.500  133.000
...                               ...      ...     ...      ...      ...
NTUH140353 2014/5/5   1           ...   96.500   91.00  102.000   93.500
NTUH160379 2016/12/7  1           ...  120.000  120.50  109.500  110.000
VGHTPE0001 2014/7/10  1           ...  170.000  140.50  152.000  149.060
VGHTPE0003 2014/7/9   1           ...  153.000  151.76  150.500  147.500
VGHTPE0078 2015/5/28  1           ...   98.500   89.50  101.500  110.500

measureTime_int                      18     19     20     21       22       23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           137.0  135.5  115.0  121.0  129.000  119.000
           2015/1/8   1           129.0  126.0  135.0  147.5  119.000  126.000
           2015/8/4   1           141.0  144.0  133.0  131.5  144.000  123.000
CGMHLK0004 2015/3/24  1           121.0  114.0  119.5  117.0  121.667  126.000
CGMHLK0007 2014/10/27 1           124.0  125.0  128.0  131.5  141.000  139.516
...                                 ...    ...    ...    ...      ...      ...
NTUH140353 2014/5/5   1           104.5   93.5   96.5   99.0   99.000  110.000
NTUH160379 2016/12/7  1           113.5  116.5  113.5  106.0  105.000  103.000
VGHTPE0001 2014/7/10  1           146.0  163.5  129.0  154.0  162.000  150.000
VGHTPE0003 2014/7/9   1           173.0  156.5  154.5  144.5  150.000  170.000
VGHTPE0078 2015/5/28  1           116.5  103.5  114.0  116.0  109.000  109.000

[526 rows x 24 columns]

# MICE 補值

In [45]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [46]:
df_mice = dfByMeasureValue.copy()
df_mice = df_mice[~df_mice.index.isin(df_mice.dropna().index)] # 拿掉完整的142筆(training data)

In [47]:
imputer = IterativeImputer(max_iter=10, random_state=0)
imputed_values = imputer.fit_transform(df_mice)

In [48]:
for col in df_mice.columns:
    missing_mask = df_mice[col].isna()
    df_mice[missing_mask] = imputed_values[missing_mask]

In [49]:
df_mice.to_csv("./preprocessed data/mice.csv")
df_mice # 1601 rows × 24 columns

measureTime_int                           0           1           2   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           131.105370  145.000000  129.892135
           2014/6/18  1           120.000000  119.000000  133.500000
           2015/1/8   1           130.000000  123.000000  118.000000
           2015/8/4   1           131.000000  116.000000  151.000000
CGMHLK0002 2014/10/27 1           115.000000  120.000000  105.000000
...                                      ...         ...         ...
VGHTPE0347 2017/4/30  1           143.336289  144.402004  142.052664
VGHTPE0348 2017/4/30  1            90.500000   98.500000   87.000000
VGHTPE0349 2017/4/30  1           121.187211  120.751609  120.870281
VGHTPE0350 2017/4/30  1           123.231587  112.000000  117.261400
VGHTPE0351 2017/4/30  1           116.500000  125.000000  121.000000

measureTime_int                           3           4           5   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           130.000000  149.000000  115.000000
           2014/6/18  1           126.447926  132.500000  122.652248
           2015/1/8   1           134.000000  106.000000  130.360776
           2015/8/4   1           138.028353  148.000000  139.000000
CGMHLK0002 2014/10/27 1           114.000000  109.000000  121.000000
...                                      ...         ...         ...
VGHTPE0347 2017/4/30  1           139.620171  143.157129  142.346261
VGHTPE0348 2017/4/30  1            87.000000   93.000000   98.000000
VGHTPE0349 2017/4/30  1           120.358537  121.273324  122.500000
VGHTPE0350 2017/4/30  1           116.727920  118.162047  118.866380
VGHTPE0351 2017/4/30  1           113.500000  115.500000  123.000000

measureTime_int                           6           7           8   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           130.333701  126.000000  130.207060
           2014/6/18  1           112.500000  128.000000  128.000000
           2015/1/8   1           162.000000  149.000000  126.000000
           2015/8/4   1           139.500000  143.000000  145.500000
CGMHLK0002 2014/10/27 1           126.500000  110.500000  117.500000
...                                      ...         ...         ...
VGHTPE0347 2017/4/30  1           148.240060  152.122124  159.935263
VGHTPE0348 2017/4/30  1           107.000000  109.667000  104.667000
VGHTPE0349 2017/4/30  1           124.000000  135.750000  130.250000
VGHTPE0350 2017/4/30  1           122.538665  125.461018  127.910648
VGHTPE0351 2017/4/30  1           123.000000  127.750000  141.500000

measureTime_int                           9   ...          14          15  \
New_MRN    Visit_Date NEWVERSION              ...
CGMHLK0001 2014/12/15 1           130.000000  ...  142.000000  128.500000
           2014/6/18  1           140.500000  ...  125.470566  115.000000
           2015/1/8   1           124.000000  ...  114.500000  129.000000
           2015/8/4   1           138.500000  ...  128.147988  128.000000
CGMHLK0002 2014/10/27 1           108.500000  ...  121.000000  127.000000
...                                      ...  ...         ...         ...
VGHTPE0347 2017/4/30  1           168.000000  ...  155.750000  166.000000
VGHTPE0348 2017/4/30  1           106.500000  ...  104.643234  106.896763
VGHTPE0349 2017/4/30  1           130.000000  ...  110.750000  113.500000
VGHTPE0350 2017/4/30  1           131.853589  ...  130.250000  129.500000
VGHTPE0351 2017/4/30  1           138.500000  ...  137.894042  136.697317

measureTime_int                           16          17          18  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           121.000000  129.763753  137.000000
           2014/6/18  1           131.000000  122.000000  125.500000
           2015/1/8   1           129.357974  137.500000  129.000000
           2015/8/4   1           115.500000  128.000000  141.000000
CGMHLK0002 2014/10/27 1           117.500000  120.500000  117.500000
...                                      ...         ...         ...
VGHTPE0347 2017/4/30  1           144.500000  152.500000  152.750000
VGHTPE0348 2017/4/30  1           107.713582  110.210618  109.509562
VGHTPE0349 2017/4/30  1           124.000000  127.579560  128.325543
VGHTPE0350 2017/4/30  1           135.500000  138.750000  139.250000
VGHTPE0351 2017/4/30  1           139.216872  138.951041  141.500036

measureTime_int                           19          20          21  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           135.500000  115.000000  121.000000
           2014/6/18  1           135.000000  136.000000  130.618448
           2015/1/8   1           126.000000  135.000000  147.500000
           2015/8/4   1           144.000000  133.000000  131.500000
CGMHLK0002 2014/10/27 1           114.500000  111.000000  108.000000
...                                      ...         ...         ...
VGHTPE0347 2017/4/30  1           173.000000  158.813415  157.538070
VGHTPE0348 2017/4/30  1           108.785931  107.667000   96.500000
VGHTPE0349 2017/4/30  1           129.235526  127.732526  126.724565
VGHTPE0350 2017/4/30  1           133.250000  132.250000  131.333000
VGHTPE0351 2017/4/30  1           141.595195  139.754707  141.289178

measureTime_int                           22          23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           129.000000  119.000000
           2014/6/18  1           123.000000  133.000000
           2015/1/8   1           119.000000  126.000000
           2015/8/4   1           144.000000  123.000000
CGMHLK0002 2014/10/27 1            97.000000  118.000000
...                                      ...         ...
VGHTPE0347 2017/4/30  1           154.293129  149.505199
VGHTPE0348 2017/4/30  1            91.500000   93.000000
VGHTPE0349 2017/4/30  1           126.221922  123.614897
VGHTPE0350 2017/4/30  1           132.500000  134.000000
VGHTPE0351 2017/4/30  1           143.000000  135.500000

[1459 rows x 24 columns]

# KNN 補值

In [50]:
from sklearn.impute import KNNImputer

In [51]:
df_knn = dfByMeasureValue.copy()
df_knn = df_knn[~df_knn.index.isin(df_knn.dropna().index)] # 拿掉完整的142筆(training data)

In [52]:
KNN_imputer = KNNImputer(n_neighbors=2, weights="uniform")
df_imputed_knn = pd.DataFrame(imputer.fit_transform(df_knn), columns=df_knn.columns).round(3)

In [53]:
for col in df_imputed_knn.columns:
    df_knn[col] = df_imputed_knn[col].values
df_knn.to_csv("./preprocessed data/knn.csv")
df_knn # 1601 rows × 24 columns

measureTime_int                        0        1        2        3        4   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           131.105  145.000  129.892  130.000  149.000
           2014/6/18  1           120.000  119.000  133.500  126.448  132.500
           2015/1/8   1           130.000  123.000  118.000  134.000  106.000
           2015/8/4   1           131.000  116.000  151.000  138.028  148.000
CGMHLK0002 2014/10/27 1           115.000  120.000  105.000  114.000  109.000
...                                   ...      ...      ...      ...      ...
VGHTPE0347 2017/4/30  1           143.336  144.402  142.053  139.620  143.157
VGHTPE0348 2017/4/30  1            90.500   98.500   87.000   87.000   93.000
VGHTPE0349 2017/4/30  1           121.187  120.752  120.870  120.359  121.273
VGHTPE0350 2017/4/30  1           123.232  112.000  117.261  116.728  118.162
VGHTPE0351 2017/4/30  1           116.500  125.000  121.000  113.500  115.500

measureTime_int                        5        6        7        8        9   \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           115.000  130.334  126.000  130.207  130.000
           2014/6/18  1           122.652  112.500  128.000  128.000  140.500
           2015/1/8   1           130.361  162.000  149.000  126.000  124.000
           2015/8/4   1           139.000  139.500  143.000  145.500  138.500
CGMHLK0002 2014/10/27 1           121.000  126.500  110.500  117.500  108.500
...                                   ...      ...      ...      ...      ...
VGHTPE0347 2017/4/30  1           142.346  148.240  152.122  159.935  168.000
VGHTPE0348 2017/4/30  1            98.000  107.000  109.667  104.667  106.500
VGHTPE0349 2017/4/30  1           122.500  124.000  135.750  130.250  130.000
VGHTPE0350 2017/4/30  1           118.866  122.539  125.461  127.911  131.854
VGHTPE0351 2017/4/30  1           123.000  123.000  127.750  141.500  138.500

measureTime_int                   ...       14       15       16       17  \
New_MRN    Visit_Date NEWVERSION  ...
CGMHLK0001 2014/12/15 1           ...  142.000  128.500  121.000  129.764
           2014/6/18  1           ...  125.471  115.000  131.000  122.000
           2015/1/8   1           ...  114.500  129.000  129.358  137.500
           2015/8/4   1           ...  128.148  128.000  115.500  128.000
CGMHLK0002 2014/10/27 1           ...  121.000  127.000  117.500  120.500
...                               ...      ...      ...      ...      ...
VGHTPE0347 2017/4/30  1           ...  155.750  166.000  144.500  152.500
VGHTPE0348 2017/4/30  1           ...  104.643  106.897  107.714  110.211
VGHTPE0349 2017/4/30  1           ...  110.750  113.500  124.000  127.580
VGHTPE0350 2017/4/30  1           ...  130.250  129.500  135.500  138.750
VGHTPE0351 2017/4/30  1           ...  137.894  136.697  139.217  138.951

measureTime_int                        18       19       20       21       22  \
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           137.000  135.500  115.000  121.000  129.000
           2014/6/18  1           125.500  135.000  136.000  130.618  123.000
           2015/1/8   1           129.000  126.000  135.000  147.500  119.000
           2015/8/4   1           141.000  144.000  133.000  131.500  144.000
CGMHLK0002 2014/10/27 1           117.500  114.500  111.000  108.000   97.000
...                                   ...      ...      ...      ...      ...
VGHTPE0347 2017/4/30  1           152.750  173.000  158.813  157.538  154.293
VGHTPE0348 2017/4/30  1           109.510  108.786  107.667   96.500   91.500
VGHTPE0349 2017/4/30  1           128.326  129.236  127.733  126.725  126.222
VGHTPE0350 2017/4/30  1           139.250  133.250  132.250  131.333  132.500
VGHTPE0351 2017/4/30  1           141.500  141.595  139.755  141.289  143.000

measureTime_int                        23
New_MRN    Visit_Date NEWVERSION
CGMHLK0001 2014/12/15 1           119.000
           2014/6/18  1           133.000
           2015/1/8   1           126.000
           2015/8/4   1           123.000
CGMHLK0002 2014/10/27 1           118.000
...                                   ...
VGHTPE0347 2017/4/30  1           149.505
VGHTPE0348 2017/4/30  1            93.000
VGHTPE0349 2017/4/30  1           123.615
VGHTPE0350 2017/4/30  1           134.000
VGHTPE0351 2017/4/30  1           135.500

[1459 rows x 24 columns]

# BERT 補值

In [54]:
# import torch
# from transformers import BertTokenizer, BertModel
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error

In [55]:
# # Sample data
# text_data = ["Your text data here", "Another text example"]
# numerical_features = [[1.0, 2.0], [3.0, 4.0]]  # Replace with your numerical features
# labels = [10.0, 20.0]  # Replace with your numerical labels

# # Step 1: Text Preprocessing
# tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# tokenized_inputs = tokenizer(text_data, padding=True, truncation=True, return_tensors="pt")

# # Step 2: BERT Model Usage
# bert_model = BertModel.from_pretrained('bert-base-uncased')
# with torch.no_grad():
#     output = bert_model(**tokenized_inputs)

# # Extract BERT embeddings
# bert_embeddings = output.last_hidden_state[:, 0, :].numpy()

# # Combine BERT embeddings with numerical features
# combined_features = torch.tensor([bert_embeddings[i].tolist() + numerical_features[i] for i in range(len(text_data))])

# # Step 3: Integration with Numerical Model
# X_train, X_test, y_train, y_test = train_test_split(combined_features, labels, test_size=0.2, random_state=42)

# # Train a simple linear regression model
# regression_model = LinearRegression()
# regression_model.fit(X_train, y_train)

# # Make predictions on the test set
# predictions = regression_model.predict(X_test)

# # Evaluate the model
# mse = mean_squared_error(y_test, predictions)
# print("Mean Squared Error:", mse)

# CTGAN

In [56]:
from ctgan import CTGAN

In [57]:
df_ctgan = df_drop_all_nan.copy() # try

In [58]:
df_ctgan = df_ctgan.reset_index()
df_ctgan_int = pd.DataFrame()

for i in range(24):
    df_ctgan_int[i] = df_ctgan[i].values
    column_name_mapping = {i: f'{i}'}
    df_ctgan_int = df_ctgan_int.rename(columns=column_name_mapping)

df_ctgan_int

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,95.5,94.5,86.0,91.0,87.0,86.0,92.333,95.5,106.0,113.667,...,114.0,106.333,98.333,94.75,103.25,106.5,104.25,111.75,112.0,106.5
1,104.0,113.0,98.0,94.0,94.0,91.0,107.500,120.0,113.0,107.000,...,95.5,113.000,99.500,103.00,100.00,117.5,121.00,118.00,107.0,112.0
2,91.0,118.0,108.0,107.0,87.0,121.0,105.000,81.0,88.5,92.000,...,84.0,85.500,104.000,117.00,111.00,117.0,102.50,106.00,92.0,100.0
3,107.0,100.0,118.0,103.0,99.0,106.0,108.000,110.0,106.5,129.000,...,115.0,114.000,113.500,116.00,118.50,127.0,119.50,130.00,130.0,130.0
4,128.0,127.0,143.0,127.0,149.0,122.0,116.000,129.0,112.5,123.000,...,116.0,122.500,111.000,127.00,121.00,126.5,136.00,128.50,130.0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,129.0,122.0,127.0,137.0,145.0,149.0,125.000,145.0,139.0,114.500,...,137.5,130.000,140.000,121.00,141.00,176.0,166.00,154.00,152.0,133.0
138,123.0,120.0,108.0,119.0,119.0,125.0,121.000,135.0,123.0,127.000,...,119.0,132.000,146.000,141.00,144.00,136.0,130.00,128.00,137.0,116.0
139,124.0,134.0,139.0,130.0,112.0,131.0,121.000,130.0,136.0,133.000,...,114.0,125.000,113.000,121.00,137.00,136.0,118.00,132.00,128.0,132.0
140,99.0,86.0,101.0,107.0,97.0,79.0,90.000,101.0,95.0,123.000,...,125.0,121.000,119.000,124.00,121.00,132.0,122.00,105.00,106.0,111.0
141,127.0,119.0,121.0,126.0,119.0,116.0,115.000,112.0,124.0,112.000,...,106.0,115.000,134.000,135.00,138.00,139.0,133.00,126.00,133.0,127.0

In [59]:
ctgan = CTGAN()
ctgan.fit(df_ctgan_int, epochs=3)

In [60]:
# Generate synthetic data
num_samples = df_ctgan.shape[0]
synthetic_data = ctgan.sample(num_samples)
synthetic_data.to_csv("./preprocessed data/ctgan.csv")
synthetic_data

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,113.954504,202.141198,115.582334,199.466801,147.898898,122.074092,144.006888,175.936759,152.110009,122.197818,...,136.258740,116.934185,170.836450,125.607610,131.884699,119.916871,119.747995,194.656659,175.085452,144.223440
1,154.685345,151.496242,85.235444,133.830505,101.645419,121.627713,111.828183,99.366309,172.582603,148.979339,...,137.655565,122.101487,103.742352,124.483241,187.083750,99.921655,142.372778,141.100475,138.486018,179.682292
2,80.972392,121.340516,131.369426,109.182411,148.920751,196.947487,117.280960,123.315681,161.737858,98.526665,...,118.313887,203.944021,119.054838,114.037470,168.809395,121.981563,175.133566,101.166249,146.123043,137.048781
3,112.103309,105.719110,212.320636,158.218491,156.226877,155.945846,154.651053,124.908673,116.166384,84.300154,...,105.763459,139.635102,145.733816,144.561586,173.741544,101.372940,128.805676,158.813676,148.189020,195.749268
4,89.348810,92.816540,118.030088,130.533889,101.576914,141.059312,95.406531,115.250213,126.757357,106.495211,...,110.613575,120.368528,86.567891,139.436347,165.974859,116.740510,132.992333,96.721242,180.586877,123.634559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,149.261148,162.742499,89.480136,168.500550,149.094026,86.942182,125.041004,111.778827,130.126988,98.304101,...,151.709915,84.191129,112.466154,171.110212,140.483930,133.150242,139.005419,108.768923,127.339611,207.945062
138,119.676782,128.857491,96.746103,87.629208,153.146899,131.435760,132.870292,136.826226,137.263574,130.939678,...,126.397172,178.823125,98.107426,82.237597,148.992976,169.221888,92.954676,118.659633,120.907440,159.491419
139,122.632563,107.088450,151.123108,159.976522,143.998628,133.105877,160.061286,73.343053,130.673919,103.533390,...,101.532017,133.982739,146.629839,148.423731,150.561963,119.210593,95.594572,89.364977,133.196746,120.351151
140,89.543497,132.567100,112.143846,168.261000,115.033031,138.667116,96.986809,128.665145,87.917542,81.938817,...,102.811849,108.258359,84.743785,184.905882,156.968020,123.547111,147.376731,83.726424,114.654800,141.166526
141,211.714497,112.993387,117.471135,95.940208,135.969701,101.779978,144.594059,65.733917,161.725079,151.542573,...,108.345433,126.318479,81.579183,126.886103,181.099995,113.457942,141.699285,121.589426,110.753019,147.655353